workflows:
  my-workflow:
    scripts:
      - name: Build ipa for distribution
        script: xcode-project build-ipa \
                    --workspace "ios\Runner.xcodeproj" \
                    --scheme "${XCODE_SCHEME?}"
    artifacts:
      - build/ios/ipa/*.ipa
