/// Flutter icons IconCust
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconCust
///      fonts:
///       - asset: fonts/IconCust.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconCust {
  IconCust._();

  static const _kFontFam = 'IconCust';
  static const String? _kFontPkg = null;

  static const IconData air_conditioner = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lamp = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tv = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
